CHATROOM_STATUS_WAIT = 0
CHATROOM_STATUS_OPEN = 100
CHATROOM_STATUS_CLOSED = 999

CHATROOM_STATUS_CHOICES = (
    (CHATROOM_STATUS_WAIT, "wait"),
    (CHATROOM_STATUS_OPEN, "open"),
    (CHATROOM_STATUS_CLOSED, "closed"),
)

CHATJOINUSER_STATUS_JOINED = 0
CHATJOINUSER_STATUS_LEFT = 999

CHATJOINUSER_STATUS_CHOICES = (
    (CHATJOINUSER_STATUS_JOINED, "join"),
    (CHATJOINUSER_STATUS_LEFT, "left"),
)
