version: '3.12'

services:
  api:
    container_name: 'api'
    build:
      context: .
    environment:
      PYTHONUNBUFFERED: 1
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb
      - redis
  postgres:
    container_name: 'postgres'
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    logging:
      driver: "none"
  mongodb:
    container_name: 'mongodb'
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    logging:
      driver: "none"
    command: mongod --quiet --logpath /dev/null
  redis:
    container_name: "redis"
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data:rw
    logging:
      driver: "none"

volumes:
  postgres_data: { }
  mongodb_data: { }
  redis_data: { }
